Trying to debug why our psh cli install is not working

diff --git a/.github/workflows/sourceops.yaml b/.github/workflows/sourceops.yaml
--- a/.github/workflows/sourceops.yaml
+++ b/.github/workflows/sourceops.yaml
@@ -25,5 +25,11 @@ jobs:
                   # source ~/.bashrc
                   # which platform
                   curl -fsS https://platform.sh/cli/installer | php
-                  curl -fsS https://raw.githubusercontent.com/gilzow/source-operations/main/setup.sh | { bash /dev/fd/3 trigger-sopupdate; } 3<&0
+                  plat=$(which platform)
+                  lastcommand=$?
+                  printf "Output from which platform is: %s\n" "${plat}"
+                  if [ 0 != lastcommand ]; then
+                    printf "which platform command failed. Here is the contents of PATH: \n%s\n" "${PATH}"
+                  fi
+                  #curl -fsS https://raw.githubusercontent.com/gilzow/source-operations/main/setup.sh | { bash /dev/fd/3 trigger-sopupdate; } 3<&0
 
