get the project ID and set it as PLATFORMSH_PROJECT_ID env var so we can associate this repo with the psh project

diff --git a/.github/workflows/sourceops.yaml b/.github/workflows/sourceops.yaml
--- a/.github/workflows/sourceops.yaml
+++ b/.github/workflows/sourceops.yaml
@@ -8,9 +8,10 @@ on:
 env:
     PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSHTOKEN }}
     PLATFORMSH_PROJECT_ID: ${{ secrets.PSHPROJID }}
+    GITHUB_TOKEN: ${{ secrets.DEVREL_TOKEN }}
 
 jobs:
-    trigger_src_op:
+    run_dm_update:
         name: Trigger Source Op
         runs-on: ubuntu-latest
         if: ${{ github.repository_owner == 'gilzow' }}
@@ -25,6 +26,25 @@ jobs:
                   # for some reason, sourcing our .bashrc file does not successfully prepend our path to PATH
                   export PATH="${HOME}/.platformsh/bin:${PATH}"
             - uses: actions/checkout@v2
+            - name: 'Get project ID'
+              run: |
+                # grab the array entries where config.url contain 'platform.sh' then map back to an array. if our
+                # array length is 1, return the entry for config.url, otherwise return error
+                integrationURL=$(gh api /repos/REPO_NAME/hooks | jq 'map(select(.config.url | contains("platform.sh"))) | if . | length == 1 then .[0].config.url else "error" end')
+                if [[ "error" == "${integrationURL} ]]; then
+                    echo "::error::Either more than one webhook, or zero webhooks were returned. I was expecting just one\n"
+                    exit 1
+                fi
+
+                projIDpttrn='\/projects\/([^\/]+)\/integrations'
+                if [[ "${integrationURL}" =~ ${projIDpttrn} ]]; then
+                     echo "PLATFORMSH_PROJECT_ID=${BASH_REMATCH[1]}" >> $GITHUB_ENV
+                     #echo "::set-output name=projectID::${BASH_REMATCH[1]}"
+                else
+                    echo "::error::We were unable to extract the project ID from the integration url of ${integrationURL}"
+                    exit 1
+                fi
+
             - name: 'Run SourceOp Tools'
               run: |
                   if [[ "${PATH}" != *".platformsh"* ]]; then
